import type {Metadata} from 'next';
import {IBM_Plex_Sans_Thai} from 'next/font/google';
import './globals.css';

const ibm = IBM_Plex_Sans_Thai({subsets:['thai'], weight: "400"});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};


export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={ibm.className +"flex min-h-screen flex-col items-center justify-between p-24"}>{children}</body>
    </html>
  );
}